# TODO: define aliased services explicitly, see: http://symfony.com/doc/current/bundles/best_practices.html#services

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Sg\DatatablesBundle\Response\DatatableResponse: '@sg_datatables.response'

    K3ssen\BaseAdminBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'

    K3ssen\BaseAdminBundle\Router\BaseAdminRouter:
        decorates: 'router'
        arguments: ['@K3ssen\BaseAdminBundle\Router\BaseAdminRouter.inner']